# data pipeline
dataset_name: "UEA"
uea_dataset_name: "ERing"
n_data_channels: 4
data_scaling: False
batch_size: 256
num_workers: 0

# misc
is_tnc_used: False
return_rc_dist: False  # True if `vibcreg_rcd` else False
use_DatasetImporterDefault: True

# augmentations
subseq_len: 135
used_augmentations:
  - "RC"
  - "AmpR"
#  - "Vshift"
AmpR_rate: 0.3
Vshift_rate: 0.5
